### ISSUE TITLE
Django 2.1 support - new release?

### ISSUE THREAD

**Issue by rlmv** [jazzband/django-model-utils#333]
## Problem

The `model` argument is removed from `DeferredAttribute` in Django 2.1, breaking `FieldTracker` when used with a defer call. However, this only applies to the 3.1.2 release - the changes in master works fine with Django 2.1.

Can you cut a new release so that we have Django 2.1 support?

Thanks!

```
Traceback (most recent call last):
  File "/Users/robertmarchman/doc-trips/fyt/core/tests/tests.py", line 33, in test_model_name_lower
    triptemplate = TripTemplate.objects.defer('name').get()
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1183, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/django/db/models/query.py", line 64, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/django/db/models/base.py", line 496, in from_db
    new = cls(*values)
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/django/db/models/base.py", line 486, in __init__
    post_init.send(sender=cls, instance=self)
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/model_utils/tracker.py", line 163, in initialize_tracker
    tracker = self.tracker_class(instance, self.fields, self.field_map)
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/model_utils/tracker.py", line 37, in __init__
    self.init_deferred_fields()
  File "/Users/robertmarchman/doc-trips/venv/lib/python3.6/site-packages/model_utils/tracker.py", line 112, in init_deferred_fields
    field_obj.field_name, None)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

## Environment

- Django Model Utils version: 3.1.2
- Django version: 2.1
- Python version: 3.6.1

**Comment by rlmv** [comment]
Moved to PR #334

**Comment by aidanlister** [comment]
Fixed in https://github.com/jazzband/django-model-utils/commit/15f9393bb21e2ea349113868d38eeb180dee97cb
