### ISSUE TITLE
Not compatible with Django 2.2.x when deferred fields are used

### ISSUE THREAD

**Issue by dmugtasimov** [jazzband/django-model-utils#374]
## Problem

Not compatible with Django 2.2.x when deferred fields are used
```
2019-06-23 18:30:33,320 ERROR django.request Internal Server Error: /admin/jobs/company/490/change/
Traceback (most recent call last):
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dmugtasimov/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1637, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1596, in _changeform_view
    media = media + inline_formset.media
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/contrib/admin/helpers.py", line 324, in media
    media = self.opts.media + self.formset.media
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/forms/formsets.py", line 394, in media
    if self.forms:
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/forms/formsets.py", line 136, in forms
    for i in range(self.total_form_count())]
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/forms/formsets.py", line 112, in total_form_count
    initial_forms = self.initial_form_count()
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/forms/models.py", line 913, in initial_form_count
    return super().initial_form_count()
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/forms/models.py", line 574, in initial_form_count
    return len(self.get_queryset())
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/db/models/query.py", line 73, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/db/models/base.py", line 513, in from_db
    new = cls(*values)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/db/models/base.py", line 503, in __init__
    post_init.send(sender=cls, instance=self)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/model_utils/tracker.py", line 163, in initialize_tracker
    tracker = self.tracker_class(instance, self.fields, self.field_map)
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/model_utils/tracker.py", line 37, in __init__
    self.init_deferred_fields()
  File "/home/dmugtasimov/.virtualenvs/dolphin-api-sD9kItjx/lib/python3.7/site-packages/model_utils/tracker.py", line 112, in init_deferred_fields
    field_obj.field_name, None)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

Two arguments:
model_utils/tracker.py
```
...
        class DeferredAttributeTracker(DescriptorMixin, DeferredAttribute):
            tracker_instance = self
...
                    field_tracker = DeferredAttributeTracker(
                        field_obj.field_name, None)
...
```

But:
django/db/models/query_utils.py
```
class DeferredAttribute:
    """
    A wrapper for a deferred-loading field. When the value is read from this
    object the first time, the query is executed.
    """
    def __init__(self, field_name):
        self.field_name = field_name
```

## Environment

- Django Model Utils version: django-model-utils==3.1.2 (3.2 has similar issue)
- Django version: Django==2.2.2
- Python version: Python 3.7.2
- Other libraries used, if any:

## Code examples

Just use deferred fields for a model with `tracker = FieldTracker()`
```
    def get_queryset(self, request):
        return super().get_queryset(request).only(
            'id', 'company_id', 'title', 'job_type_id', 'job_type__name',
            'locations__id', 'locations__name', 'url')
```

**Comment by dmugtasimov** [comment]
Please, let me know if it can be fixed in a need future, otherwise I should consider to use alternative library temporarily.

**Comment by tiwariayush** [comment]
It has been fixed. You need to do version up to `3.2.0`
